### ISSUE TITLE
カブ価予測API

### ISSUE THREAD

**Issue by webdev-jp-net** [osakana9114/acnh-turnip-tracker#6]
カブ価予測のAPIが提供されていた
https://github.com/elxris/Turnip-Calculator/issues/72#issuecomment-617483396

つかわせてもらえば、自前で作らなくてもChart.jsに反映できる。

Github
https://github.com/elxris/Turnip-Calculator

Turnip Prophet（動いている画面）
https://turnipprophet.io/index.html

**Comment by osakana9114** [comment]
おおー！めっちゃいいじゃないですか🥺
見つけてくださってありがとうございます✨
これなら組み込めそうですよね✨

**Comment by webdev-jp-net** [comment]
@osakana9114 良い感じですね！
気になっているのは、APIなので、オフラインでは取得できないところです。

**Comment by webdev-jp-net** [comment]
オフライン対応する強みがこれといって無いので、
API採用 + ネットワークにつないで予測グラフ描画
の方向で実装をすすめます。

**Comment by webdev-jp-net** [comment]
TODO:

Next.jsのサーバでCORSエラーがでるので、プロキシを設定する。

https://qiita.com/lelouch99v/items/3dc11676bb9c23457d41

**Comment by webdev-jp-net** [comment]
📝 APIとの連携設定はひととおりおわっているので
この課題は #14 をマージしたタイミングでclose
