### ISSUE TITLE
開発環境のportを.envで設定できるようにする

### ISSUE THREAD

**Issue by webdev-jp-net** [osakana9114/acnh-turnip-tracker#7]
3000portがバッティングしがち。
各自、.envで任意の値を設定できるようにする。

**Comment by webdev-jp-net** [comment]
@osakana9114 `/app/.env`を設置して、起動するポート、hostname、証明書がある場合は https起動ができるようになりました。

https://github.com/osakana9114/acnh-turnip-tracker/blob/master/app/.env.example

お手すきでテストいただいて、問題なさそうなら closeおねがいいたします。

**Comment by osakana9114** [comment]
@webdev-jp-net 
ありがとうございます！
ローカルでためしてみます🙇‍♀️

**Comment by osakana9114** [comment]
@webdev-jp-net 
だいぶ間あいてしまいました💦
ローカルで起動できました、ありがとうございます！
